
language: c

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc

before_install:
  sudo apt-get install --assume-yes --quiet gcc-multilib

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

notifications:
    email: false
    