
sudo: false
language: C
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7.3         
  env:
    - MATRIX_EVAL="CC=gcc-7.3 && CXX=g++-7.3"

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ./hopfieldann ../data/hopf02.dat
