
sudo: false
language: C
compiler: g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6.3         
  env:
    - MATRIX_EVAL="CC=g++-6 && CXX=g++-6"

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

notifications:
    email: false
    